/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utfpr.rmi.atividade06;

import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class UrnaRMI extends javax.swing.JFrame {

    /**
     * Creates new form ClienteRMI
     */
    public UrnaRMI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbVotar1 = new javax.swing.JButton();
        jbConectar = new javax.swing.JButton();
        jbVotar = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        label1 = new java.awt.Label();
        jbComputarVotos = new javax.swing.JButton();

        jbVotar1.setText("Votar");
        jbVotar1.setEnabled(false);
        jbVotar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVotar1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbConectar.setText("Conectar Servidor");
        jbConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConectarActionPerformed(evt);
            }
        });

        jbVotar.setText("Votar");
        jbVotar.setEnabled(false);
        jbVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVotarActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Mario Andrade");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Joice Bonifacio");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        label1.setText("Eleições 2021");

        jbComputarVotos.setText("Enviar para servidor");
        jbComputarVotos.setEnabled(false);
        jbComputarVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComputarVotosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbConectar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbVotar, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbComputarVotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConectar)
                    .addComponent(jbVotar)
                    .addComponent(jbComputarVotos))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void habilitarObjetos(){
            jbConectar.setEnabled(false);
            jbVotar.setEnabled(true);
            jbComputarVotos.setEnabled(true);

    }
    
    private void jbVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVotarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:     
            if(jRadioButton1.isSelected()==false && jRadioButton2.isSelected()==false){
                JOptionPane.showMessageDialog(rootPane, "Selecione um candidato primeiro");
            }
            
            else if(jRadioButton1.isSelected()==true){
                JOptionPane.showMessageDialog(rootPane, "Voto realzado para o candidato: " +jRadioButton1.getText());
                
                votosMario=votosMario+1;
                
              //  stub.computarVotos(jRadioButton1.getText());
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Voto realzado para o candidato: " +jRadioButton2.getText());
                votosJoice=votosJoice+1;
            }
            
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jbVotarActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:         
            jRadioButton2.setSelected(false);
        } catch (Exception ex) {
            System.out.println(ex);
        }
            
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
              
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jbConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConectarActionPerformed
        // TODO add your handling code here:
        try {

            registro = LocateRegistry.getRegistry("localhost", 1099);

            stub = (Servicos) registro.lookup("classeServicos");

            habilitarObjetos();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbConectarActionPerformed

    private void jbVotar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVotar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbVotar1ActionPerformed

    private void jbComputarVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComputarVotosActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(rootPane, "Votação encerrada, votos encaminhados para o servidor");
        
        try {
            stub.computarVotos(jRadioButton1.getText(), votosMario);
            stub.computarVotos(jRadioButton2.getText(), votosJoice);
        } catch (RemoteException ex) {
            Logger.getLogger(UrnaRMI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jbVotar.setEnabled(false);
        jbComputarVotos.setEnabled(false);
        
    }//GEN-LAST:event_jbComputarVotosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrnaRMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrnaRMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrnaRMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrnaRMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrnaRMI().setVisible(true);
            }
        });
    }

    // minhas variaveis
    Registry registro;
    Servicos stub;
    static Integer votosMario=0;
    static Integer votosJoice=0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton jbComputarVotos;
    private javax.swing.JButton jbConectar;
    private javax.swing.JButton jbVotar;
    private javax.swing.JButton jbVotar1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
